name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4
        
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        run:
      - name:
        run:

  ci:
    runs-on: ubuntu-latest
    steps:
      - name:
        run:
      - name:
        run:
      - name:
        run:
